version: '2'

services:
  cassandra:
    image: palantirtechnologies/docker-cassandra-atlasdb:$CASSANDRA_VERSION
    environment:
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9160:9160"
      - "9042:9042"